## Pinned, redistributable TextMate grammar packages for Matter.
##
## This file is generated by ``tools/regenerate_grammars.py`` from
## ``tools/grammar_manifest.json``.  The catalog is network-free at runtime;
## each listed archive contains only allowlisted grammar files and attribution.

import std/options

type
  SourcePackage* = object ## A pinned grammar source package and local archive.
    namespace*: string
    name*: string
    version*: string
    targetPlatform*: string
    sourceKind*: string
    sourceArchiveSha256*: string
    sourceVsixSha256*: string
    licenseId*: string
    repositoryUrl*: string
    licenseUrl*: string
    downloadUrl*: string
    dataArchivePath*: string
    archiveSha256*: string

  OpenVsxPackage* = SourcePackage ## Compatibility name for Open VSX packages.

  GrammarContribution* = object ## A grammar file retained in a local archive.
    displayName*: string
    languageId*: string
    scopeName*: string
    grammarPath*: string
    archiveMember*: string
    packageKey*: string
    dataArchivePath*: string
    isPrimary*: bool

  LanguageGrammar* = GrammarContribution ## Compatibility name for grammar records.

  MoeGrammarMapping* = object ## One current Moe ``SourceLanguage`` mode.
    modeName*: string
    scopeName*: string

const
  openVsxApiBaseUrl* = "https://open-vsx.org/api"
  vscodeCppPackage* = SourcePackage(
    namespace: "vscode",
    name: "cpp",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "b70b8b007d21c89f929c32eaa89cf15e710723e091be682418c125cc93733c36",
    sourceVsixSha256: "b70b8b007d21c89f929c32eaa89cf15e710723e091be682418c125cc93733c36",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/cpp",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/cpp/1.95.3/file/vscode.cpp-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-cpp-1.95.3.zip",
    archiveSha256: "7b024dbe5a320cd7e485e8625391eacc4785d0e5956cd14fa41f8e949c921639",
  )
  vscodeCsharpPackage* = SourcePackage(
    namespace: "vscode",
    name: "csharp",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "384dd3d44b3ebb8ff377c4bfa7a4a2d500a48c22fa30e4697b23d3e2158192a7",
    sourceVsixSha256: "384dd3d44b3ebb8ff377c4bfa7a4a2d500a48c22fa30e4697b23d3e2158192a7",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/csharp",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/csharp/1.95.3/file/vscode.csharp-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-csharp-1.95.3.zip",
    archiveSha256: "603a657a83b27cacace31331ba47dd9525fa08f6707c99d845845438fd9a0d7a",
  )
  vscodeDiffPackage* = SourcePackage(
    namespace: "vscode",
    name: "diff",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "ce799c16ac50165bbf2a07fbb353f7a25f3df9d52f91b75dcfe4017d56389335",
    sourceVsixSha256: "ce799c16ac50165bbf2a07fbb353f7a25f3df9d52f91b75dcfe4017d56389335",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/diff",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/diff/1.95.3/file/vscode.diff-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-diff-1.95.3.zip",
    archiveSha256: "49182229d72bc6285f872ec63d4e240c7cade9b68982d65dfd6e7d737bb7149d",
  )
  vscodeDockerPackage* = SourcePackage(
    namespace: "vscode",
    name: "docker",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "5de2f31e7e8e9c64b17d0b2eb915a5c14653904376a06d07f2229890fe296078",
    sourceVsixSha256: "5de2f31e7e8e9c64b17d0b2eb915a5c14653904376a06d07f2229890fe296078",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/docker",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/docker/1.95.3/file/vscode.docker-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-docker-1.95.3.zip",
    archiveSha256: "657c04fd5525120701c06d37c671db6ada72c52c4a128d121b6f7781ceb6b2d3",
  )
  vscodeGitBasePackage* = SourcePackage(
    namespace: "vscode",
    name: "git-base",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "956c41e4e8377a6b113a6a64fcd5308deaad44a827288f6bfcd5cf1c83037483",
    sourceVsixSha256: "956c41e4e8377a6b113a6a64fcd5308deaad44a827288f6bfcd5cf1c83037483",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/git-base",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/git-base/1.95.3/file/vscode.git-base-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-git-base-1.95.3.zip",
    archiveSha256: "48561cf839fa501ff236c8a39ae8197281e0b1a14dcc45a73ff3bf4fa0fdfb28",
  )
  vscodeGoPackage* = SourcePackage(
    namespace: "vscode",
    name: "go",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "af091f9e53479ccd5e3dcee8b770973c7a1cc40d70afaf3aa1066d112a95a400",
    sourceVsixSha256: "af091f9e53479ccd5e3dcee8b770973c7a1cc40d70afaf3aa1066d112a95a400",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/go",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl: "https://open-vsx.org/api/vscode/go/1.95.3/file/vscode.go-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-go-1.95.3.zip",
    archiveSha256: "0c7149f5b1aecce0365883fba0caf678fb00ace5b62298cf57de1f095a2ffd6b",
  )
  vscodeHtmlPackage* = SourcePackage(
    namespace: "vscode",
    name: "html",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "193c7d03374f3f8b71f01dabae05c93b86069b28521cbb18fad0beab6eb42732",
    sourceVsixSha256: "193c7d03374f3f8b71f01dabae05c93b86069b28521cbb18fad0beab6eb42732",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/html",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/html/1.95.3/file/vscode.html-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-html-1.95.3.zip",
    archiveSha256: "b5989bd0a9af1e5b8246e86ccc1f61e1297abe14e87f273f31d2fd72f8b033c6",
  )
  vscodeJavaPackage* = SourcePackage(
    namespace: "vscode",
    name: "java",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "885469b3e7da89f8b8d0eae58b9ce065a59e67d84f507855460f7d6c9a67b17b",
    sourceVsixSha256: "885469b3e7da89f8b8d0eae58b9ce065a59e67d84f507855460f7d6c9a67b17b",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/java",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/java/1.95.3/file/vscode.java-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-java-1.95.3.zip",
    archiveSha256: "f640e5a5c733f54b4e208db8c593eee06aaa65232bade496d64f66c58c92c8bd",
  )
  vscodeJavascriptPackage* = SourcePackage(
    namespace: "vscode",
    name: "javascript",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "df55b5174c57ec057d78d4b9ddd225cc36095b6fc845f1a0df87f1e13dfb64b2",
    sourceVsixSha256: "df55b5174c57ec057d78d4b9ddd225cc36095b6fc845f1a0df87f1e13dfb64b2",
    licenseId: "MIT",
    repositoryUrl:
      "https://github.com/microsoft/vscode/tree/1.95.3/extensions/javascript",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/javascript/1.95.3/file/vscode.javascript-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-javascript-1.95.3.zip",
    archiveSha256: "dff4088a3152174b57a1ef94df6c547f29e8de4520c0685b1e23f0ccc39b9917",
  )
  vscodeLatexPackage* = SourcePackage(
    namespace: "vscode",
    name: "latex",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "b5b1ef21dfd8ef6e65a89549225ee767ab4a4a1544082e5a159e95d03f78cfa6",
    sourceVsixSha256: "b5b1ef21dfd8ef6e65a89549225ee767ab4a4a1544082e5a159e95d03f78cfa6",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/latex",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/latex/1.95.3/file/vscode.latex-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-latex-1.95.3.zip",
    archiveSha256: "dcc74b1a3daaf9f65d5f3266b8ac7e66898339054078f6a3f5e6124353f387be",
  )
  vscodeLogPackage* = SourcePackage(
    namespace: "vscode",
    name: "log",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "cc3908ef8cf97a86dbed68c1bf2729ef17e18ff691aa8294d330bac45733da35",
    sourceVsixSha256: "cc3908ef8cf97a86dbed68c1bf2729ef17e18ff691aa8294d330bac45733da35",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/log",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/log/1.95.3/file/vscode.log-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-log-1.95.3.zip",
    archiveSha256: "3f720b5318e84f90ae3001f5cdc7387750ddd164e9d609a4bca83f230d3b8bff",
  )
  vscodeLuaPackage* = SourcePackage(
    namespace: "vscode",
    name: "lua",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "90a58f6cfe76fcd391d9fe672d339f6a275f13ec91ce10316d6befe41a78b57e",
    sourceVsixSha256: "90a58f6cfe76fcd391d9fe672d339f6a275f13ec91ce10316d6befe41a78b57e",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/lua",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/lua/1.95.3/file/vscode.lua-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-lua-1.95.3.zip",
    archiveSha256: "e2cfbf8400e95d2e697aee22f6eec4c1e60549d3f02480d78f03ee060b8de6dd",
  )
  vscodeMarkdownPackage* = SourcePackage(
    namespace: "vscode",
    name: "markdown",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "53591b889e8941db812f263d8e5eaa34ec83718e399ecd7a1e178410bd3877a9",
    sourceVsixSha256: "53591b889e8941db812f263d8e5eaa34ec83718e399ecd7a1e178410bd3877a9",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/markdown",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/markdown/1.95.3/file/vscode.markdown-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-markdown-1.95.3.zip",
    archiveSha256: "95822e75f233c3cb8f2ea6ddce19c05ff549f759520e6c3c1dd2eb4eaa780480",
  )
  vscodeRustPackage* = SourcePackage(
    namespace: "vscode",
    name: "rust",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "23dd92f554f968fbeefe9976fdb9996c35b2152cf0778cf74bd1019a5ed4b8eb",
    sourceVsixSha256: "23dd92f554f968fbeefe9976fdb9996c35b2152cf0778cf74bd1019a5ed4b8eb",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/rust",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/rust/1.95.3/file/vscode.rust-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-rust-1.95.3.zip",
    archiveSha256: "0b7c04d3d1db48f704d99e921f358dd48c51cbe5af6d2828132ef21174f14dc0",
  )
  vscodeShellscriptPackage* = SourcePackage(
    namespace: "vscode",
    name: "shellscript",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "b60e2bf7de39524bf0608653583b5e0360fe78e3ec59e94f2bd1b9255e89c38d",
    sourceVsixSha256: "b60e2bf7de39524bf0608653583b5e0360fe78e3ec59e94f2bd1b9255e89c38d",
    licenseId: "MIT",
    repositoryUrl:
      "https://github.com/microsoft/vscode/tree/1.95.3/extensions/shellscript",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/shellscript/1.95.3/file/vscode.shellscript-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-shellscript-1.95.3.zip",
    archiveSha256: "0647323e43b474ac9ab341d56e3d6e72344d57a732a605f301af860d85ec67c3",
  )
  vscodeTypescriptPackage* = SourcePackage(
    namespace: "vscode",
    name: "typescript",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "493019c0375ad6d46a8811e041d70f68eb57ed5e5a9698125e4691eaf6f2d8fc",
    sourceVsixSha256: "493019c0375ad6d46a8811e041d70f68eb57ed5e5a9698125e4691eaf6f2d8fc",
    licenseId: "MIT",
    repositoryUrl:
      "https://github.com/microsoft/vscode/tree/1.95.3/extensions/typescript",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/typescript/1.95.3/file/vscode.typescript-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-typescript-1.95.3.zip",
    archiveSha256: "1423fa3c0f941e649e02488c0b6a24bf70d806cc2af012844fed7c5004d60798",
  )
  vscodeXmlPackage* = SourcePackage(
    namespace: "vscode",
    name: "xml",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "34024416f2583fa48f7f1a8ab7f30b37986eea54d9a7a6be1f25aff8507dd0a1",
    sourceVsixSha256: "34024416f2583fa48f7f1a8ab7f30b37986eea54d9a7a6be1f25aff8507dd0a1",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/xml",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/xml/1.95.3/file/vscode.xml-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-xml-1.95.3.zip",
    archiveSha256: "dcef1eb2caaf909e0cec050073117df67d6a435ce8c1218b9635d1e39372ca49",
  )
  vscodeYamlPackage* = SourcePackage(
    namespace: "vscode",
    name: "yaml",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "1c60f93adad36f20de0696bc75f8b3829f3fc4c760f4d8022ec9f934436bbeb0",
    sourceVsixSha256: "1c60f93adad36f20de0696bc75f8b3829f3fc4c760f4d8022ec9f934436bbeb0",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/yaml",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/yaml/1.95.3/file/vscode.yaml-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-yaml-1.95.3.zip",
    archiveSha256: "431b7eb6a3f33552e4bbdc1c5942ea91b69e3a5a6b629be9bd1c2f14914eeefc",
  )
  vscodeJsonPackage* = SourcePackage(
    namespace: "vscode",
    name: "json",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "53667e2cc9875c6872f8d7eff75314c46f8c0a30398efd9e7bec437b7cb928c3",
    sourceVsixSha256: "53667e2cc9875c6872f8d7eff75314c46f8c0a30398efd9e7bec437b7cb928c3",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/json",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/json/1.95.3/file/vscode.json-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-json-1.95.3.zip",
    archiveSha256: "cfee614c69f7801dcadc28137dcd9da809551792305efd09a4bcaee61da5d5ca",
  )
  vscodePythonPackage* = SourcePackage(
    namespace: "vscode",
    name: "python",
    version: "1.95.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "37c2a0cdfa668bd4dc37265d7d172300a20350098651b1843ee220a30c5e2d88",
    sourceVsixSha256: "37c2a0cdfa668bd4dc37265d7d172300a20350098651b1843ee220a30c5e2d88",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/microsoft/vscode/tree/1.95.3/extensions/python",
    licenseUrl: "https://github.com/microsoft/vscode/blob/1.95.3/LICENSE.txt",
    downloadUrl:
      "https://open-vsx.org/api/vscode/python/1.95.3/file/vscode.python-1.95.3.vsix",
    dataArchivePath: "data/grammars/vscode-python-1.95.3.zip",
    archiveSha256: "ff70d22418c81b8050d6043111144f7827a3e46d673b198930e6417e8e91712f",
  )
  nimVscodePackage* = SourcePackage(
    namespace: "nimsaem",
    name: "nimvscode",
    version: "0.1.26",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "e0ac9d990c992f1937bb6f7a81d7a2bc68cf9484563ee9105bba0980472768ea",
    sourceVsixSha256: "e0ac9d990c992f1937bb6f7a81d7a2bc68cf9484563ee9105bba0980472768ea",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/saem/vscode-nim",
    licenseUrl: "https://github.com/saem/vscode-nim/blob/main/LICENSE",
    downloadUrl:
      "https://open-vsx.org/api/nimsaem/nimvscode/0.1.26/file/nimsaem.nimvscode-0.1.26.vsix",
    dataArchivePath: "data/grammars/nimsaem-nimvscode-0.1.26.zip",
    archiveSha256: "662bb479dce8d0b0179dcffba488a7e580f4158b379b83d3f69eca8475b694f8",
  )
  fishPackage* = SourcePackage(
    namespace: "bmalehorn",
    name: "vscode-fish",
    version: "1.0.49",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "e15419680986f2c30b6b0f25e9a4067ca4ee158eff797b771e0f73f7e534751c",
    sourceVsixSha256: "e15419680986f2c30b6b0f25e9a4067ca4ee158eff797b771e0f73f7e534751c",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/bmalehorn/vscode-fish",
    licenseUrl: "https://github.com/bmalehorn/vscode-fish/blob/master/LICENSE",
    downloadUrl:
      "https://open-vsx.org/api/bmalehorn/vscode-fish/1.0.49/file/bmalehorn.vscode-fish-1.0.49.vsix",
    dataArchivePath: "data/grammars/bmalehorn-vscode-fish-1.0.49.zip",
    archiveSha256: "7e2c80f1e2944adbfbf44b5c5293dda6d5eda6943cf2dcac4b63a147c0c7c8e5",
  )
  haskellPackage* = SourcePackage(
    namespace: "haskell",
    name: "language-haskell",
    version: "3.8.0",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "c031af18a23e603c246d8295d228e7077f8dc163d902ec0b378329155dfb285b",
    sourceVsixSha256: "c031af18a23e603c246d8295d228e7077f8dc163d902ec0b378329155dfb285b",
    licenseId: "BSD-3-Clause",
    repositoryUrl: "https://github.com/haskell/language-haskell",
    licenseUrl: "https://github.com/haskell/language-haskell/blob/master/LICENSE",
    downloadUrl:
      "https://open-vsx.org/api/haskell/language-haskell/3.8.0/file/haskell.language-haskell-3.8.0.vsix",
    dataArchivePath: "data/grammars/haskell-language-haskell-3.8.0.zip",
    archiveSha256: "e628e90e9457c86a1965e0d6150041f5fcab7c39f85c9cc207066fc98a9f1648",
  )
  hyprlangPackage* = SourcePackage(
    namespace: "fireblast",
    name: "hyprlang-vscode",
    version: "0.0.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "6678df68388684886957c911030f10b5ff749d72ffe319c5c259ca6f4d6c7d29",
    sourceVsixSha256: "6678df68388684886957c911030f10b5ff749d72ffe319c5c259ca6f4d6c7d29",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/TheFireBlast/hyprlang-vscode",
    licenseUrl: "https://github.com/TheFireBlast/hyprlang-vscode/blob/main/LICENSE",
    downloadUrl:
      "https://open-vsx.org/api/fireblast/hyprlang-vscode/0.0.3/file/fireblast.hyprlang-vscode-0.0.3.vsix",
    dataArchivePath: "data/grammars/fireblast-hyprlang-vscode-0.0.3.zip",
    archiveSha256: "87fdef6101daf2ce2f7bdf2fcac621a8d78851f10700b5e9a671a61a5739f39f",
  )
  tomlPackage* = SourcePackage(
    namespace: "tamasfe",
    name: "even-better-toml",
    version: "0.21.2",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "f3dc44f1c551edef397a79f0f8c5db4066c6a547e210b5c3cec4400bf173b008",
    sourceVsixSha256: "f3dc44f1c551edef397a79f0f8c5db4066c6a547e210b5c3cec4400bf173b008",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/tamasfe/taplo",
    licenseUrl: "https://github.com/tamasfe/taplo/blob/master/LICENSE",
    downloadUrl:
      "https://open-vsx.org/api/tamasfe/even-better-toml/0.21.2/file/tamasfe.even-better-toml-0.21.2.vsix",
    dataArchivePath: "data/grammars/tamasfe-even-better-toml-0.21.2.zip",
    archiveSha256: "b2cd8b38c03b8cb81e6244c9735659e698bdfd663b3c720f7d24747d08265389",
  )
  lispPackage* = SourcePackage(
    namespace: "jeff-hykin",
    name: "better-lisp-syntax",
    version: "0.0.2",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "068ef8c3cfca0b1e09fa8af50d60533ecf4ef08ba51e721ca0f54434526f7e2d",
    sourceVsixSha256: "068ef8c3cfca0b1e09fa8af50d60533ecf4ef08ba51e721ca0f54434526f7e2d",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/jeff-hykin/better-lisp-syntax",
    licenseUrl: "https://github.com/jeff-hykin/better-lisp-syntax/blob/master/LICENSE",
    downloadUrl:
      "https://open-vsx.org/api/jeff-hykin/better-lisp-syntax/0.0.2/file/jeff-hykin.better-lisp-syntax-0.0.2.vsix",
    dataArchivePath: "data/grammars/jeff-hykin-better-lisp-syntax-0.0.2.zip",
    archiveSha256: "10a5726be557ad7d12d2ddcf9c5a181729c512ba1dd1679c10d7902e48a8ae2a",
  )
  astroPackage* = SourcePackage(
    namespace: "astro-build",
    name: "astro-vscode",
    version: "2.16.20",
    targetPlatform: "alpine-arm64",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "64fb9007bcfeb5cd64e63aaaecea99ab9a7d26ba6c41b3c1b8130536b304c3ce",
    sourceVsixSha256: "64fb9007bcfeb5cd64e63aaaecea99ab9a7d26ba6c41b3c1b8130536b304c3ce",
    licenseId: "MIT",
    repositoryUrl:
      "https://github.com/withastro/astro/tree/main/packages/language-tools/vscode",
    licenseUrl: "https://github.com/withastro/astro/blob/main/LICENSE",
    downloadUrl:
      "https://open-vsx.org/api/astro-build/astro-vscode/alpine-arm64/2.16.20/file/astro-build.astro-vscode-2.16.20@alpine-arm64.vsix",
    dataArchivePath: "data/grammars/astro-build-astro-vscode-2.16.20.zip",
    archiveSha256: "c6706b169dfd1858e47e7bff021cc0c562ecd6f09d164d750682dd059fd6aaae",
  )
  tclPackage* = SourcePackage(
    namespace: "bitwisecook",
    name: "tcl",
    version: "0.4.3",
    targetPlatform: "",
    sourceKind: "vsix",
    sourceArchiveSha256:
      "1d380f8f2e9e4f7cc3756656e2b0d7338bc5e67667a61ccdbff4253b7f70ae7d",
    sourceVsixSha256: "1d380f8f2e9e4f7cc3756656e2b0d7338bc5e67667a61ccdbff4253b7f70ae7d",
    licenseId: "MIT",
    repositoryUrl: "https://github.com/bitwisecook/vscode-tcl",
    licenseUrl: "https://github.com/bitwisecook/vscode-tcl/blob/main/LICENSE",
    downloadUrl:
      "https://github.com/bitwisecook/vscode-tcl/releases/download/0.4.3/tcl-0.4.3.vsix",
    dataArchivePath: "data/grammars/bitwisecook-tcl-0.4.3.zip",
    archiveSha256: "29a11ac4b58a2b6c8ef991d32becc2c98945841eb4efb0f8e2929e7558a1c596",
  )
  terraformSyntaxPackage* = SourcePackage(
    namespace: "hashicorp",
    name: "syntax",
    version: "0.7.1",
    targetPlatform: "",
    sourceKind: "github-archive",
    sourceArchiveSha256:
      "5dc1b0b2bb2e67afa2e9f78d1b019ee08d4cb5f118da20be7ee0579a8d66df68",
    sourceVsixSha256: "",
    licenseId: "MPL-2.0",
    repositoryUrl: "https://github.com/hashicorp/syntax/tree/v0.7.1",
    licenseUrl: "https://github.com/hashicorp/syntax/blob/v0.7.1/LICENSE",
    downloadUrl: "https://github.com/hashicorp/syntax/archive/refs/tags/v0.7.1.zip",
    dataArchivePath: "data/grammars/hashicorp-syntax-0.7.1.zip",
    archiveSha256: "49480deb6e4d421d5c7289b5498d89ba9a90ba8337813dc6099662d75a2ba365",
  )
  terraformPlanPackage* = SourcePackage(
    namespace: "aryairani",
    name: "tofu-plan-highlight",
    version: "0.1.0",
    targetPlatform: "",
    sourceKind: "github-archive",
    sourceArchiveSha256:
      "080508d09e4d4ec936b2601a6c9b5b79014a1a1d13a759e5204bbbbd5302b757",
    sourceVsixSha256: "",
    licenseId: "MIT",
    repositoryUrl:
      "https://github.com/aryairani/tofu-plan-highlight/tree/0edf2419e1323bd96db23712a960d2990dd3a323",
    licenseUrl:
      "https://github.com/aryairani/tofu-plan-highlight/blob/0edf2419e1323bd96db23712a960d2990dd3a323/LICENSE",
    downloadUrl:
      "https://github.com/aryairani/tofu-plan-highlight/archive/0edf2419e1323bd96db23712a960d2990dd3a323.zip",
    dataArchivePath: "data/grammars/aryairani-tofu-plan-highlight-0.1.0.zip",
    archiveSha256: "346b967a5f388d48855a4b802ee432bb25995941b1fc282d193177f648778764",
  )

  knownPackages* = [
    vscodeCppPackage, vscodeCsharpPackage, vscodeDiffPackage, vscodeDockerPackage,
    vscodeGitBasePackage, vscodeGoPackage, vscodeHtmlPackage, vscodeJavaPackage,
    vscodeJavascriptPackage, vscodeLatexPackage, vscodeLogPackage, vscodeLuaPackage,
    vscodeMarkdownPackage, vscodeRustPackage, vscodeShellscriptPackage,
    vscodeTypescriptPackage, vscodeXmlPackage, vscodeYamlPackage, vscodeJsonPackage,
    vscodePythonPackage, nimVscodePackage, fishPackage, haskellPackage, hyprlangPackage,
    tomlPackage, lispPackage, astroPackage, tclPackage, terraformSyntaxPackage,
    terraformPlanPackage,
  ]

  cGrammar* = GrammarContribution(
    displayName: "C",
    languageId: "c",
    scopeName: "source.c",
    grammarPath: "./syntaxes/c.tmLanguage.json",
    archiveMember: "grammar/syntaxes/c.tmLanguage.json",
    packageKey: "vscode.cpp",
    dataArchivePath: "data/grammars/vscode-cpp-1.95.3.zip",
    isPrimary: true,
  )
  cppEmbeddedMacroGrammar* = GrammarContribution(
    displayName: "C++ Embedded Macro Support",
    languageId: "cpp",
    scopeName: "source.cpp.embedded.macro",
    grammarPath: "./syntaxes/cpp.embedded.macro.tmLanguage.json",
    archiveMember: "grammar/syntaxes/cpp.embedded.macro.tmLanguage.json",
    packageKey: "vscode.cpp",
    dataArchivePath: "data/grammars/vscode-cpp-1.95.3.zip",
    isPrimary: false,
  )
  cppGrammar* = GrammarContribution(
    displayName: "C++",
    languageId: "cpp",
    scopeName: "source.cpp",
    grammarPath: "./syntaxes/cpp.tmLanguage.json",
    archiveMember: "grammar/syntaxes/cpp.tmLanguage.json",
    packageKey: "vscode.cpp",
    dataArchivePath: "data/grammars/vscode-cpp-1.95.3.zip",
    isPrimary: true,
  )
  cPlatformGrammar* = GrammarContribution(
    displayName: "C Platform Support",
    languageId: "",
    scopeName: "source.c.platform",
    grammarPath: "./syntaxes/platform.tmLanguage.json",
    archiveMember: "grammar/syntaxes/platform.tmLanguage.json",
    packageKey: "vscode.cpp",
    dataArchivePath: "data/grammars/vscode-cpp-1.95.3.zip",
    isPrimary: false,
  )
  csharpGrammar* = GrammarContribution(
    displayName: "C#",
    languageId: "csharp",
    scopeName: "source.cs",
    grammarPath: "./syntaxes/csharp.tmLanguage.json",
    archiveMember: "grammar/syntaxes/csharp.tmLanguage.json",
    packageKey: "vscode.csharp",
    dataArchivePath: "data/grammars/vscode-csharp-1.95.3.zip",
    isPrimary: true,
  )
  diffGrammar* = GrammarContribution(
    displayName: "Diff",
    languageId: "diff",
    scopeName: "source.diff",
    grammarPath: "./syntaxes/diff.tmLanguage.json",
    archiveMember: "grammar/syntaxes/diff.tmLanguage.json",
    packageKey: "vscode.diff",
    dataArchivePath: "data/grammars/vscode-diff-1.95.3.zip",
    isPrimary: true,
  )
  dockerGrammar* = GrammarContribution(
    displayName: "Dockerfile",
    languageId: "dockerfile",
    scopeName: "source.dockerfile",
    grammarPath: "./syntaxes/docker.tmLanguage.json",
    archiveMember: "grammar/syntaxes/docker.tmLanguage.json",
    packageKey: "vscode.docker",
    dataArchivePath: "data/grammars/vscode-docker-1.95.3.zip",
    isPrimary: true,
  )
  gitCommitGrammar* = GrammarContribution(
    displayName: "Git commit message",
    languageId: "git-commit",
    scopeName: "text.git-commit",
    grammarPath: "./syntaxes/git-commit.tmLanguage.json",
    archiveMember: "grammar/syntaxes/git-commit.tmLanguage.json",
    packageKey: "vscode.git-base",
    dataArchivePath: "data/grammars/vscode-git-base-1.95.3.zip",
    isPrimary: true,
  )
  gitRebaseGrammar* = GrammarContribution(
    displayName: "Git rebase todo",
    languageId: "git-rebase",
    scopeName: "text.git-rebase",
    grammarPath: "./syntaxes/git-rebase.tmLanguage.json",
    archiveMember: "grammar/syntaxes/git-rebase.tmLanguage.json",
    packageKey: "vscode.git-base",
    dataArchivePath: "data/grammars/vscode-git-base-1.95.3.zip",
    isPrimary: true,
  )
  gitIgnoreGrammar* = GrammarContribution(
    displayName: "Git ignore",
    languageId: "ignore",
    scopeName: "source.ignore",
    grammarPath: "./syntaxes/ignore.tmLanguage.json",
    archiveMember: "grammar/syntaxes/ignore.tmLanguage.json",
    packageKey: "vscode.git-base",
    dataArchivePath: "data/grammars/vscode-git-base-1.95.3.zip",
    isPrimary: true,
  )
  goGrammar* = GrammarContribution(
    displayName: "Go",
    languageId: "go",
    scopeName: "source.go",
    grammarPath: "./syntaxes/go.tmLanguage.json",
    archiveMember: "grammar/syntaxes/go.tmLanguage.json",
    packageKey: "vscode.go",
    dataArchivePath: "data/grammars/vscode-go-1.95.3.zip",
    isPrimary: true,
  )
  htmlBasicGrammar* = GrammarContribution(
    displayName: "HTML basic support",
    languageId: "",
    scopeName: "text.html.basic",
    grammarPath: "./syntaxes/html.tmLanguage.json",
    archiveMember: "grammar/syntaxes/html.tmLanguage.json",
    packageKey: "vscode.html",
    dataArchivePath: "data/grammars/vscode-html-1.95.3.zip",
    isPrimary: false,
  )
  htmlGrammar* = GrammarContribution(
    displayName: "HTML",
    languageId: "html",
    scopeName: "text.html.derivative",
    grammarPath: "./syntaxes/html-derivative.tmLanguage.json",
    archiveMember: "grammar/syntaxes/html-derivative.tmLanguage.json",
    packageKey: "vscode.html",
    dataArchivePath: "data/grammars/vscode-html-1.95.3.zip",
    isPrimary: true,
  )
  javaGrammar* = GrammarContribution(
    displayName: "Java",
    languageId: "java",
    scopeName: "source.java",
    grammarPath: "./syntaxes/java.tmLanguage.json",
    archiveMember: "grammar/syntaxes/java.tmLanguage.json",
    packageKey: "vscode.java",
    dataArchivePath: "data/grammars/vscode-java-1.95.3.zip",
    isPrimary: true,
  )
  jsxGrammar* = GrammarContribution(
    displayName: "JavaScript React",
    languageId: "javascriptreact",
    scopeName: "source.js.jsx",
    grammarPath: "./syntaxes/JavaScriptReact.tmLanguage.json",
    archiveMember: "grammar/syntaxes/JavaScriptReact.tmLanguage.json",
    packageKey: "vscode.javascript",
    dataArchivePath: "data/grammars/vscode-javascript-1.95.3.zip",
    isPrimary: true,
  )
  javascriptGrammar* = GrammarContribution(
    displayName: "JavaScript",
    languageId: "javascript",
    scopeName: "source.js",
    grammarPath: "./syntaxes/JavaScript.tmLanguage.json",
    archiveMember: "grammar/syntaxes/JavaScript.tmLanguage.json",
    packageKey: "vscode.javascript",
    dataArchivePath: "data/grammars/vscode-javascript-1.95.3.zip",
    isPrimary: true,
  )
  javascriptRegexpGrammar* = GrammarContribution(
    displayName: "JavaScript regular expression support",
    languageId: "",
    scopeName: "source.js.regexp",
    grammarPath: "./syntaxes/Regular Expressions (JavaScript).tmLanguage",
    archiveMember: "grammar/syntaxes/Regular Expressions (JavaScript).tmLanguage",
    packageKey: "vscode.javascript",
    dataArchivePath: "data/grammars/vscode-javascript-1.95.3.zip",
    isPrimary: false,
  )
  texGrammar* = GrammarContribution(
    displayName: "TeX support",
    languageId: "tex",
    scopeName: "text.tex",
    grammarPath: "./syntaxes/TeX.tmLanguage.json",
    archiveMember: "grammar/syntaxes/TeX.tmLanguage.json",
    packageKey: "vscode.latex",
    dataArchivePath: "data/grammars/vscode-latex-1.95.3.zip",
    isPrimary: false,
  )
  latexGrammar* = GrammarContribution(
    displayName: "LaTeX",
    languageId: "latex",
    scopeName: "text.tex.latex",
    grammarPath: "./syntaxes/LaTeX.tmLanguage.json",
    archiveMember: "grammar/syntaxes/LaTeX.tmLanguage.json",
    packageKey: "vscode.latex",
    dataArchivePath: "data/grammars/vscode-latex-1.95.3.zip",
    isPrimary: true,
  )
  bibtexGrammar* = GrammarContribution(
    displayName: "BibTeX support",
    languageId: "",
    scopeName: "text.bibtex",
    grammarPath: "./syntaxes/Bibtex.tmLanguage.json",
    archiveMember: "grammar/syntaxes/Bibtex.tmLanguage.json",
    packageKey: "vscode.latex",
    dataArchivePath: "data/grammars/vscode-latex-1.95.3.zip",
    isPrimary: false,
  )
  markdownLatexGrammar* = GrammarContribution(
    displayName: "Markdown LaTeX support",
    languageId: "",
    scopeName: "text.tex.markdown_latex_combined",
    grammarPath: "./syntaxes/markdown-latex-combined.tmLanguage.json",
    archiveMember: "grammar/syntaxes/markdown-latex-combined.tmLanguage.json",
    packageKey: "vscode.latex",
    dataArchivePath: "data/grammars/vscode-latex-1.95.3.zip",
    isPrimary: false,
  )
  cppEmbeddedLatexGrammar* = GrammarContribution(
    displayName: "C++ embedded LaTeX support",
    languageId: "",
    scopeName: "source.cpp.embedded.latex",
    grammarPath: "./syntaxes/cpp-grammar-bailout.tmLanguage.json",
    archiveMember: "grammar/syntaxes/cpp-grammar-bailout.tmLanguage.json",
    packageKey: "vscode.latex",
    dataArchivePath: "data/grammars/vscode-latex-1.95.3.zip",
    isPrimary: false,
  )
  logGrammar* = GrammarContribution(
    displayName: "Log",
    languageId: "log",
    scopeName: "text.log",
    grammarPath: "./syntaxes/log.tmLanguage.json",
    archiveMember: "grammar/syntaxes/log.tmLanguage.json",
    packageKey: "vscode.log",
    dataArchivePath: "data/grammars/vscode-log-1.95.3.zip",
    isPrimary: true,
  )
  luaGrammar* = GrammarContribution(
    displayName: "Lua",
    languageId: "lua",
    scopeName: "source.lua",
    grammarPath: "./syntaxes/lua.tmLanguage.json",
    archiveMember: "grammar/syntaxes/lua.tmLanguage.json",
    packageKey: "vscode.lua",
    dataArchivePath: "data/grammars/vscode-lua-1.95.3.zip",
    isPrimary: true,
  )
  markdownGrammar* = GrammarContribution(
    displayName: "Markdown",
    languageId: "markdown",
    scopeName: "text.html.markdown",
    grammarPath: "./syntaxes/markdown.tmLanguage.json",
    archiveMember: "grammar/syntaxes/markdown.tmLanguage.json",
    packageKey: "vscode.markdown",
    dataArchivePath: "data/grammars/vscode-markdown-1.95.3.zip",
    isPrimary: true,
  )
  rustGrammar* = GrammarContribution(
    displayName: "Rust",
    languageId: "rust",
    scopeName: "source.rust",
    grammarPath: "./syntaxes/rust.tmLanguage.json",
    archiveMember: "grammar/syntaxes/rust.tmLanguage.json",
    packageKey: "vscode.rust",
    dataArchivePath: "data/grammars/vscode-rust-1.95.3.zip",
    isPrimary: true,
  )
  shellGrammar* = GrammarContribution(
    displayName: "Shell",
    languageId: "shellscript",
    scopeName: "source.shell",
    grammarPath: "./syntaxes/shell-unix-bash.tmLanguage.json",
    archiveMember: "grammar/syntaxes/shell-unix-bash.tmLanguage.json",
    packageKey: "vscode.shellscript",
    dataArchivePath: "data/grammars/vscode-shellscript-1.95.3.zip",
    isPrimary: true,
  )
  typescriptGrammar* = GrammarContribution(
    displayName: "TypeScript",
    languageId: "typescript",
    scopeName: "source.ts",
    grammarPath: "./syntaxes/TypeScript.tmLanguage.json",
    archiveMember: "grammar/syntaxes/TypeScript.tmLanguage.json",
    packageKey: "vscode.typescript",
    dataArchivePath: "data/grammars/vscode-typescript-1.95.3.zip",
    isPrimary: true,
  )
  tsxGrammar* = GrammarContribution(
    displayName: "TypeScript React",
    languageId: "typescriptreact",
    scopeName: "source.tsx",
    grammarPath: "./syntaxes/TypeScriptReact.tmLanguage.json",
    archiveMember: "grammar/syntaxes/TypeScriptReact.tmLanguage.json",
    packageKey: "vscode.typescript",
    dataArchivePath: "data/grammars/vscode-typescript-1.95.3.zip",
    isPrimary: true,
  )
  typescriptJsdocGrammar* = GrammarContribution(
    displayName: "TypeScript documentation support",
    languageId: "",
    scopeName: "documentation.injection.ts",
    grammarPath: "./syntaxes/jsdoc.ts.injection.tmLanguage.json",
    archiveMember: "grammar/syntaxes/jsdoc.ts.injection.tmLanguage.json",
    packageKey: "vscode.typescript",
    dataArchivePath: "data/grammars/vscode-typescript-1.95.3.zip",
    isPrimary: false,
  )
  javascriptJsdocGrammar* = GrammarContribution(
    displayName: "JavaScript JSX documentation support",
    languageId: "",
    scopeName: "documentation.injection.js.jsx",
    grammarPath: "./syntaxes/jsdoc.js.injection.tmLanguage.json",
    archiveMember: "grammar/syntaxes/jsdoc.js.injection.tmLanguage.json",
    packageKey: "vscode.typescript",
    dataArchivePath: "data/grammars/vscode-typescript-1.95.3.zip",
    isPrimary: false,
  )
  xmlGrammar* = GrammarContribution(
    displayName: "XML",
    languageId: "xml",
    scopeName: "text.xml",
    grammarPath: "./syntaxes/xml.tmLanguage.json",
    archiveMember: "grammar/syntaxes/xml.tmLanguage.json",
    packageKey: "vscode.xml",
    dataArchivePath: "data/grammars/vscode-xml-1.95.3.zip",
    isPrimary: true,
  )
  xslGrammar* = GrammarContribution(
    displayName: "XSL",
    languageId: "",
    scopeName: "text.xml.xsl",
    grammarPath: "./syntaxes/xsl.tmLanguage.json",
    archiveMember: "grammar/syntaxes/xsl.tmLanguage.json",
    packageKey: "vscode.xml",
    dataArchivePath: "data/grammars/vscode-xml-1.95.3.zip",
    isPrimary: false,
  )
  yamlGrammar* = GrammarContribution(
    displayName: "YAML",
    languageId: "yaml",
    scopeName: "source.yaml",
    grammarPath: "./syntaxes/yaml.tmLanguage.json",
    archiveMember: "grammar/syntaxes/yaml.tmLanguage.json",
    packageKey: "vscode.yaml",
    dataArchivePath: "data/grammars/vscode-yaml-1.95.3.zip",
    isPrimary: true,
  )
  jsonGrammar* = GrammarContribution(
    displayName: "JSON",
    languageId: "json",
    scopeName: "source.json",
    grammarPath: "./syntaxes/JSON.tmLanguage.json",
    archiveMember: "grammar/syntaxes/JSON.tmLanguage.json",
    packageKey: "vscode.json",
    dataArchivePath: "data/grammars/vscode-json-1.95.3.zip",
    isPrimary: true,
  )
  jsoncGrammar* = GrammarContribution(
    displayName: "JSON with comments",
    languageId: "jsonc",
    scopeName: "source.json.comments",
    grammarPath: "./syntaxes/JSONC.tmLanguage.json",
    archiveMember: "grammar/syntaxes/JSONC.tmLanguage.json",
    packageKey: "vscode.json",
    dataArchivePath: "data/grammars/vscode-json-1.95.3.zip",
    isPrimary: true,
  )
  pythonGrammar* = GrammarContribution(
    displayName: "Python",
    languageId: "python",
    scopeName: "source.python",
    grammarPath: "./syntaxes/MagicPython.tmLanguage.json",
    archiveMember: "grammar/syntaxes/MagicPython.tmLanguage.json",
    packageKey: "vscode.python",
    dataArchivePath: "data/grammars/vscode-python-1.95.3.zip",
    isPrimary: true,
  )
  pythonRegexpGrammar* = GrammarContribution(
    displayName: "Python regular expression support",
    languageId: "",
    scopeName: "source.regexp.python",
    grammarPath: "./syntaxes/MagicRegExp.tmLanguage.json",
    archiveMember: "grammar/syntaxes/MagicRegExp.tmLanguage.json",
    packageKey: "vscode.python",
    dataArchivePath: "data/grammars/vscode-python-1.95.3.zip",
    isPrimary: false,
  )
  nimGrammar* = GrammarContribution(
    displayName: "Nim",
    languageId: "nim",
    scopeName: "source.nim",
    grammarPath: "./syntaxes/nim.json",
    archiveMember: "grammar/syntaxes/nim.json",
    packageKey: "nimsaem.nimvscode",
    dataArchivePath: "data/grammars/nimsaem-nimvscode-0.1.26.zip",
    isPrimary: true,
  )
  nimbleGrammar* = GrammarContribution(
    displayName: "Nimble",
    languageId: "nimble",
    scopeName: "source.nimble",
    grammarPath: "./syntaxes/nimble.json",
    archiveMember: "grammar/syntaxes/nimble.json",
    packageKey: "nimsaem.nimvscode",
    dataArchivePath: "data/grammars/nimsaem-nimvscode-0.1.26.zip",
    isPrimary: false,
  )
  fishGrammar* = GrammarContribution(
    displayName: "Fish",
    languageId: "fish",
    scopeName: "source.fish",
    grammarPath: "./syntaxes/fish.tmLanguage.json",
    archiveMember: "grammar/syntaxes/fish.tmLanguage.json",
    packageKey: "bmalehorn.vscode-fish",
    dataArchivePath: "data/grammars/bmalehorn-vscode-fish-1.0.49.zip",
    isPrimary: true,
  )
  fishCodeblockGrammar* = GrammarContribution(
    displayName: "Fish Markdown code block support",
    languageId: "",
    scopeName: "markdown.fish.codeblock",
    grammarPath: "./syntaxes/codeblock.json",
    archiveMember: "grammar/syntaxes/codeblock.json",
    packageKey: "bmalehorn.vscode-fish",
    dataArchivePath: "data/grammars/bmalehorn-vscode-fish-1.0.49.zip",
    isPrimary: false,
  )
  haskellGrammar* = GrammarContribution(
    displayName: "Haskell",
    languageId: "haskell",
    scopeName: "source.haskell",
    grammarPath: "./syntaxes/haskell.json",
    archiveMember: "grammar/syntaxes/haskell.json",
    packageKey: "haskell.language-haskell",
    dataArchivePath: "data/grammars/haskell-language-haskell-3.8.0.zip",
    isPrimary: true,
  )
  cabalGrammar* = GrammarContribution(
    displayName: "Cabal",
    languageId: "cabal",
    scopeName: "source.cabal",
    grammarPath: "./syntaxes/cabal.json",
    archiveMember: "grammar/syntaxes/cabal.json",
    packageKey: "haskell.language-haskell",
    dataArchivePath: "data/grammars/haskell-language-haskell-3.8.0.zip",
    isPrimary: false,
  )
  hyprlangGrammar* = GrammarContribution(
    displayName: "Hyprlang",
    languageId: "hyprlang",
    scopeName: "source.hyprlang",
    grammarPath: "./syntaxes/hyprlang.tmGrammar.json",
    archiveMember: "grammar/syntaxes/hyprlang.tmGrammar.json",
    packageKey: "fireblast.hyprlang-vscode",
    dataArchivePath: "data/grammars/fireblast-hyprlang-vscode-0.0.3.zip",
    isPrimary: true,
  )
  tomlGrammar* = GrammarContribution(
    displayName: "TOML",
    languageId: "toml",
    scopeName: "source.toml",
    grammarPath: "./toml.tmLanguage.json",
    archiveMember: "grammar/toml.tmLanguage.json",
    packageKey: "tamasfe.even-better-toml",
    dataArchivePath: "data/grammars/tamasfe-even-better-toml-0.21.2.zip",
    isPrimary: true,
  )
  tomlFrontmatterGrammar* = GrammarContribution(
    displayName: "TOML frontmatter support",
    languageId: "",
    scopeName: "markdown.toml.frontmatter.codeblock",
    grammarPath: "./toml.frontmatter.tmLanguage.json",
    archiveMember: "grammar/toml.frontmatter.tmLanguage.json",
    packageKey: "tamasfe.even-better-toml",
    dataArchivePath: "data/grammars/tamasfe-even-better-toml-0.21.2.zip",
    isPrimary: false,
  )
  tomlMarkdownGrammar* = GrammarContribution(
    displayName: "TOML Markdown code block support",
    languageId: "",
    scopeName: "markdown.toml.codeblock",
    grammarPath: "./toml.markdown.tmLanguage.json",
    archiveMember: "grammar/toml.markdown.tmLanguage.json",
    packageKey: "tamasfe.even-better-toml",
    dataArchivePath: "data/grammars/tamasfe-even-better-toml-0.21.2.zip",
    isPrimary: false,
  )
  lispGrammar* = GrammarContribution(
    displayName: "Lisp",
    languageId: "lisp",
    scopeName: "source.lisp",
    grammarPath: "./autogenerated/lisp.tmLanguage.json",
    archiveMember: "grammar/autogenerated/lisp.tmLanguage.json",
    packageKey: "jeff-hykin.better-lisp-syntax",
    dataArchivePath: "data/grammars/jeff-hykin-better-lisp-syntax-0.0.2.zip",
    isPrimary: true,
  )
  astroGrammar* = GrammarContribution(
    displayName: "Astro",
    languageId: "astro",
    scopeName: "source.astro",
    grammarPath: "./syntaxes/astro.tmLanguage.json",
    archiveMember: "grammar/syntaxes/astro.tmLanguage.json",
    packageKey: "astro-build.astro-vscode",
    dataArchivePath: "data/grammars/astro-build-astro-vscode-2.16.20.zip",
    isPrimary: true,
  )
  astroMarkdownGrammar* = GrammarContribution(
    displayName: "Astro Markdown support",
    languageId: "",
    scopeName: "text.html.markdown.astro",
    grammarPath: "./syntaxes/markdown.astro.tmLanguage.json",
    archiveMember: "grammar/syntaxes/markdown.astro.tmLanguage.json",
    packageKey: "astro-build.astro-vscode",
    dataArchivePath: "data/grammars/astro-build-astro-vscode-2.16.20.zip",
    isPrimary: false,
  )
  astroMdxGrammar* = GrammarContribution(
    displayName: "Astro MDX support",
    languageId: "",
    scopeName: "source.mdx.astro",
    grammarPath: "./syntaxes/mdx.astro.tmLanguage.json",
    archiveMember: "grammar/syntaxes/mdx.astro.tmLanguage.json",
    packageKey: "astro-build.astro-vscode",
    dataArchivePath: "data/grammars/astro-build-astro-vscode-2.16.20.zip",
    isPrimary: false,
  )
  tclGrammar* = GrammarContribution(
    displayName: "Tcl",
    languageId: "tcl",
    scopeName: "source.tcl",
    grammarPath: "./out/syntaxes/tcl.json",
    archiveMember: "grammar/out/syntaxes/tcl.json",
    packageKey: "bitwisecook.tcl",
    dataArchivePath: "data/grammars/bitwisecook-tcl-0.4.3.zip",
    isPrimary: true,
  )
  terraformGrammar* = GrammarContribution(
    displayName: "Terraform",
    languageId: "terraform",
    scopeName: "source.hcl.terraform",
    grammarPath: "./syntaxes/terraform.tmGrammar.json",
    archiveMember: "grammar/syntaxes/terraform.tmGrammar.json",
    packageKey: "hashicorp.syntax",
    dataArchivePath: "data/grammars/hashicorp-syntax-0.7.1.zip",
    isPrimary: true,
  )
  terraformPlanGrammar* = GrammarContribution(
    displayName: "OpenTofu / Terraform Plan",
    languageId: "tofu-plan",
    scopeName: "source.tofu-plan",
    grammarPath: "./syntaxes/tofu-plan.tmLanguage.json",
    archiveMember: "grammar/syntaxes/tofu-plan.tmLanguage.json",
    packageKey: "aryairani.tofu-plan-highlight",
    dataArchivePath: "data/grammars/aryairani-tofu-plan-highlight-0.1.0.zip",
    isPrimary: true,
  )

  knownGrammars* = [
    cGrammar, cppEmbeddedMacroGrammar, cppGrammar, cPlatformGrammar, csharpGrammar,
    diffGrammar, dockerGrammar, gitCommitGrammar, gitRebaseGrammar, gitIgnoreGrammar,
    goGrammar, htmlBasicGrammar, htmlGrammar, javaGrammar, jsxGrammar,
    javascriptGrammar, javascriptRegexpGrammar, texGrammar, latexGrammar, bibtexGrammar,
    markdownLatexGrammar, cppEmbeddedLatexGrammar, logGrammar, luaGrammar,
    markdownGrammar, rustGrammar, shellGrammar, typescriptGrammar, tsxGrammar,
    typescriptJsdocGrammar, javascriptJsdocGrammar, xmlGrammar, xslGrammar, yamlGrammar,
    jsonGrammar, jsoncGrammar, pythonGrammar, pythonRegexpGrammar, nimGrammar,
    nimbleGrammar, fishGrammar, fishCodeblockGrammar, haskellGrammar, cabalGrammar,
    hyprlangGrammar, tomlGrammar, tomlFrontmatterGrammar, tomlMarkdownGrammar,
    lispGrammar, astroGrammar, astroMarkdownGrammar, astroMdxGrammar, tclGrammar,
    terraformGrammar, terraformPlanGrammar,
  ]

  moeGrammarMappings* = [
    MoeGrammarMapping(modeName: "astro", scopeName: "source.astro"),
    MoeGrammarMapping(modeName: "c", scopeName: "source.c"),
    MoeGrammarMapping(modeName: "commitEditMsg", scopeName: "text.git-commit"),
    MoeGrammarMapping(modeName: "cpp", scopeName: "source.cpp"),
    MoeGrammarMapping(modeName: "csharp", scopeName: "source.cs"),
    MoeGrammarMapping(modeName: "diff", scopeName: "source.diff"),
    MoeGrammarMapping(modeName: "dockerfile", scopeName: "source.dockerfile"),
    MoeGrammarMapping(modeName: "fish", scopeName: "source.fish"),
    MoeGrammarMapping(modeName: "gitRebaseTodo", scopeName: "text.git-rebase"),
    MoeGrammarMapping(modeName: "gitignore", scopeName: "source.ignore"),
    MoeGrammarMapping(modeName: "go", scopeName: "source.go"),
    MoeGrammarMapping(modeName: "haskell", scopeName: "source.haskell"),
    MoeGrammarMapping(modeName: "html", scopeName: "text.html.derivative"),
    MoeGrammarMapping(modeName: "hyprland", scopeName: "source.hyprlang"),
    MoeGrammarMapping(modeName: "java", scopeName: "source.java"),
    MoeGrammarMapping(modeName: "javascript", scopeName: "source.js"),
    MoeGrammarMapping(modeName: "jsx", scopeName: "source.js.jsx"),
    MoeGrammarMapping(modeName: "latex", scopeName: "text.tex.latex"),
    MoeGrammarMapping(modeName: "lisp", scopeName: "source.lisp"),
    MoeGrammarMapping(modeName: "log", scopeName: "text.log"),
    MoeGrammarMapping(modeName: "lua", scopeName: "source.lua"),
    MoeGrammarMapping(modeName: "markdown", scopeName: "text.html.markdown"),
    MoeGrammarMapping(modeName: "nim", scopeName: "source.nim"),
    MoeGrammarMapping(modeName: "python", scopeName: "source.python"),
    MoeGrammarMapping(modeName: "rust", scopeName: "source.rust"),
    MoeGrammarMapping(modeName: "shell", scopeName: "source.shell"),
    MoeGrammarMapping(modeName: "tcl", scopeName: "source.tcl"),
    MoeGrammarMapping(modeName: "toml", scopeName: "source.toml"),
    MoeGrammarMapping(modeName: "yaml", scopeName: "source.yaml"),
    MoeGrammarMapping(modeName: "json", scopeName: "source.json"),
    MoeGrammarMapping(modeName: "jsonc", scopeName: "source.json.comments"),
    MoeGrammarMapping(modeName: "typescript", scopeName: "source.ts"),
    MoeGrammarMapping(modeName: "tsx", scopeName: "source.tsx"),
    MoeGrammarMapping(modeName: "xml", scopeName: "text.xml"),
    MoeGrammarMapping(modeName: "zsh", scopeName: "source.shell"),
  ]

func extensionId*(package: SourcePackage): string =
  ## Returns the source extension identifier, such as ``vscode.cpp``.
  package.namespace & "." & package.name

func versionMetadataUrl*(namespace, name, version: string): string =
  ## Returns the Open VSX metadata URL for a specific extension version.
  openVsxApiBaseUrl & "/" & namespace & "/" & name & "/" & version

func versionMetadataUrl*(package: SourcePackage): string =
  ## Returns the conventional Open VSX metadata URL for this package.
  versionMetadataUrl(package.namespace, package.name, package.version)

func latestMetadataUrl*(package: SourcePackage): string =
  ## Returns the conventional Open VSX latest-version metadata URL.
  versionMetadataUrl(package.namespace, package.name, "latest")

func vsixDownloadUrl*(namespace, name, version: string): string =
  ## Returns a direct versioned Open VSX VSIX URL.
  let extension = namespace & "." & name & "-" & version & ".vsix"
  versionMetadataUrl(namespace, name, version) & "/file/" & extension

func vsixDownloadUrl*(package: SourcePackage): string =
  ## Returns this package's pinned URL when its source is a VSIX.
  package.downloadUrl

func sourceArchiveUrl*(package: SourcePackage): string =
  ## Returns this package's exact pinned upstream source archive URL.
  package.downloadUrl

func findGrammar*(scopeName: string): Option[GrammarContribution] =
  ## Finds an archived grammar by its TextMate scope name.
  for grammar in knownGrammars:
    if grammar.scopeName == scopeName:
      return some(grammar)
  none(GrammarContribution)

func findMoeGrammar*(modeName: string): Option[GrammarContribution] =
  ## Finds the primary grammar imported for a current Moe language mode.
  for mapping in moeGrammarMappings:
    if mapping.modeName == modeName:
      return findGrammar(mapping.scopeName)
  none(GrammarContribution)

iterator importedGrammars*(modeName: string): GrammarContribution =
  ## Yields a Moe mode's primary grammar followed by support grammars bundled
  ## with the same source package.  Callers can read every yielded member from
  ## its ``dataArchivePath`` without downloading anything.
  let primary = findMoeGrammar(modeName)
  if primary.isSome:
    yield primary.get
    for grammar in knownGrammars:
      if grammar.packageKey == primary.get.packageKey and
          grammar.scopeName != primary.get.scopeName:
        yield grammar
